name: poetry export requirements.txt

on:
  push:
    branches: [main]
    paths-ignore:
      - "requirements.txt"
      - "poetry.lock"
      - "*.md"
      - "docs/**"
      - ".env.example"
      - "LICENSE"
      - "Makefile"
      - ".gitignore"

permissions:
  contents: write

jobs:
  export-requirements-txt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: divideprojects/poetry-export-requirements-action@v1
        with:
          without-hashes: false
          outfile-name: requirements.txt
      - name: Commit report
        run: |
          git config --global user.name 'alan890104'
          git config --global user.email 'alan890104@users.noreply.github.com'
          git add requirements.txt
          git commit -am "Sync requirements.txt from poetry.lock"
          git push
